package oprf

import (
	"errors"

	"github.com/gtank/ristretto255"
)

// VerifiableBlindEvaluate takes the server's private key and a blinded element and returns an evaluated element to be
// transmitted to the client, plus a proof.
func VerifiableBlindEvaluate(domain string, d *ristretto255.Scalar, blindedElement *ristretto255.Element) (evaluatedElement *ristretto255.Element, c, s *ristretto255.Scalar, err error) {
	if blindedElement.Equal(ristretto255.NewIdentityElement()) == 1 {
		return nil, nil, nil, errors.New("oprf: blinded element is identity")
	}

	q := ristretto255.NewIdentityElement().ScalarBaseMult(d)

	evaluatedElement = ristretto255.NewIdentityElement().ScalarMult(d, blindedElement)
	if evaluatedElement.Equal(ristretto255.NewIdentityElement()) == 1 {
		return nil, nil, nil, errors.New("oprf: evaluated element is identity")
	}

	blindedElements := []*ristretto255.Element{blindedElement}
	evaluatedElements := []*ristretto255.Element{evaluatedElement}
	c, s = generateProof(domain, d, ristretto255.NewGeneratorElement(), q, blindedElements, evaluatedElements)
	return evaluatedElement, c, s, nil
}

// VerifiableFinalize takes the client's secret input, the blind scalar and blinded element generated by Blind, the
// server's public key, the evaluated element and proof returned by VerifiableBlindEvaluate, the number of bytes to
// generate, and returns n bytes of PRF output, or an error if the proof cannot be verified.
func VerifiableFinalize(domain string, input []byte, blind *ristretto255.Scalar, q, evaluatedElement, blindedElement *ristretto255.Element, c, s *ristretto255.Scalar, n int) ([]byte, error) {
	if q.Equal(ristretto255.NewIdentityElement()) == 1 {
		return nil, errors.New("oprf: public key is identity")
	}

	if blindedElement.Equal(ristretto255.NewIdentityElement()) == 1 {
		return nil, errors.New("oprf: blinded element is identity")
	}

	if evaluatedElement.Equal(ristretto255.NewIdentityElement()) == 1 {
		return nil, errors.New("oprf: evaluated element is identity")
	}

	blindedElements := []*ristretto255.Element{blindedElement}
	evaluatedElements := []*ristretto255.Element{evaluatedElement}
	if !verifyProof(domain, ristretto255.NewGeneratorElement(), q, blindedElements, evaluatedElements, c, s) {
		return nil, errors.New("oprf: invalid proof")
	}

	return Finalize(domain, input, blind, evaluatedElement, n)
}
